services:

  orthanc-ref:
    image: orthancteam/orthanc:26.1.0
    depends_on: [orthanc-ref-db]
    restart: unless-stopped
    ports: ["8142:8042"]
    volumes: ["storage-orthanc-ref:/var/lib/orthanc/db"]
    environment:
      VERBOSE_ENABLED: "true"
      ORTHANC__POSTGRESQL__HOST: "orthanc-ref-db"
      ORTHANC_JSON: |
        {
          "Name": "Orthanc-ref",
          "AuthenticationEnabled": false,
          "OverwriteInstances": true
        }

  orthanc-new:
    image: ${ORTHANC_IMAGE_UNDER_TESTS:-orthancteam/orthanc:latest}
    depends_on: [orthanc-new-db]
    restart: unless-stopped
    ports: ["8143:8042"]
    volumes: ["storage-orthanc-new:/var/lib/orthanc/db"]
    environment:
      VERBOSE_ENABLED: "true"
      ORTHANC__POSTGRESQL__HOST: "orthanc-new-db"
      ORTHANC_JSON: |
        {
          "Name": "Orthanc-under-tests",
          "AuthenticationEnabled": false,
          "OverwriteInstances": true
        }


  orthanc-ref-db:
    image: postgres:18
    restart: unless-stopped
    volumes: 
      - "storage-db-ref:/var/lib/postgresql/18/docker"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

  orthanc-new-db:
    image: postgres:18
    restart: unless-stopped
    volumes: 
      - "storage-db-new:/var/lib/postgresql/18/docker"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"


  orthanc-ref-s3:
    image: orthancteam/orthanc:26.1.0
    depends_on: [orthanc-ref-db-s3]
    restart: unless-stopped
    ports: ["8242:8042"]
    environment:
      VERBOSE_ENABLED: "true"
      ORTHANC__POSTGRESQL__HOST: "orthanc-ref-db-s3"
      ORTHANC_JSON: |
        {
          "Name": "Orthanc-ref-s3",
          "AuthenticationEnabled": false,
          "OverwriteInstances": true,
          "AwsS3Storage": {
            "BucketName": "default-bucket",
            "Region": "eu-west-1",
            "AccessKey": "s3-like-admin",
            "SecretKey": "change-me",
            "Endpoint": "http://toxiproxy-ref-s3:8333",
            "VirtualAddressing": false
          }
        }

  orthanc-new-s3:
    image: ${ORTHANC_IMAGE_UNDER_TESTS:-orthancteam/orthanc:latest}
    depends_on: [orthanc-new-db-s3]
    restart: unless-stopped
    ports: ["8243:8042"]
    environment:
      VERBOSE_ENABLED: "true"
      ORTHANC__POSTGRESQL__HOST: "orthanc-new-db-s3"
      ORTHANC_JSON: |
        {
          "Name": "Orthanc-under-tests-s3",
          "AuthenticationEnabled": false,
          "OverwriteInstances": true,
          "AwsS3Storage": {
            "BucketName": "default-bucket",
            "Region": "eu-west-1",
            "AccessKey": "s3-like-admin",
            "SecretKey": "change-me",
            "Endpoint": "http://toxiproxy-new-s3:8333",
            "VirtualAddressing": false
          }
        }


  orthanc-ref-db-s3:
    image: postgres:18
    restart: unless-stopped
    volumes: 
      - "storage-db-ref-s3:/var/lib/postgresql/18/docker"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

  orthanc-new-db-s3:
    image: postgres:18
    restart: unless-stopped
    volumes: 
      - "storage-db-new-s3:/var/lib/postgresql/18/docker"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"


  s3-like-ref:
    image: chrislusf/seaweedfs
    # ports: [8333:8333]
    environment:
      - AWS_ACCESS_KEY_ID=s3-like-admin
      - AWS_SECRET_ACCESS_KEY=change-me
      - S3_BUCKET=default-bucket
    volumes:
        - storage-ref-s3:/data
    command: mini -dir=/data


  s3-like-new:
    image: chrislusf/seaweedfs
    ports: [8333:8333]
    environment:
      - AWS_ACCESS_KEY_ID=s3-like-admin
      - AWS_SECRET_ACCESS_KEY=change-me
      - S3_BUCKET=default-bucket
    volumes:
        - storage-new-s3:/data
    command: mini -dir=/data


  toxiproxy-ref-s3:
      depends_on: 
          - s3-like-ref
      image: ghcr.io/shopify/toxiproxy

  toxiproxy-new-s3:
      depends_on: 
          - s3-like-new
      image: ghcr.io/shopify/toxiproxy


  toxiproxy-config:
      image: curlimages/curl
      depends_on: 
          - toxiproxy-ref-s3
          - toxiproxy-new-s3
      restart: on-failure
      entrypoint: >
          sh -c "sleep 3;
          curl -sf -X POST http://toxiproxy-ref-s3:8474/proxies -H 'Content-Type: application/json' -d '{\"name\":\"s3-like\",\"listen\":\"0.0.0.0:8333\",\"upstream\":\"s3-like-ref:8333\"}';
          curl -sf -X POST http://toxiproxy-ref-s3:8474/proxies/s3-like/toxics -H 'Content-Type: application/json' -d '{\"type\":\"latency\",\"attributes\":{\"latency\":10,\"jitter\":0}}';
          curl -sf -X POST http://toxiproxy-new-s3:8474/proxies -H 'Content-Type: application/json' -d '{\"name\":\"s3-like\",\"listen\":\"0.0.0.0:8333\",\"upstream\":\"s3-like-new:8333\"}';
          curl -sf -X POST http://toxiproxy-new-s3:8474/proxies/s3-like/toxics -H 'Content-Type: application/json' -d '{\"type\":\"latency\",\"attributes\":{\"latency\":10,\"jitter\":0}}';
          "

volumes:
  storage-orthanc-ref:
  storage-orthanc-new:
  storage-db-ref:
  storage-db-new:
  storage-ref-s3:
  storage-new-s3:
  storage-db-ref-s3:
  storage-db-new-s3:  