#!/bin/bash

# Without Docker:
# python ./Tests/Run.py --force

set -ex

if [ ! -f "./getscu-3.6.5" ]; then
    # This binary was generated by running Linux Standard Base on
    # "Resources/DcmtkTools" in the Orthanc source distribution,
    # as DCMTK 3.6.0 does not contain "getscu"
    wget http://orthanc.osimis.io/ThirdPartyDownloads/linux-standard-base/getscu-3.6.5
    chmod +x ./getscu-3.6.5
fi

sudo docker run --rm -t -i -p 5000:5000 -p 5001:5001 \
     -v `pwd`:/tmp/tests:ro \
     -v `pwd`/getscu-3.6.5:/usr/bin/getscu:ro \
     --entrypoint python jodogne/orthanc-tests \
     /tmp/tests/Tests/Run.py --docker $*
